// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | SmallHeroSlice
  | FaqSliceSlice
  | ContentSlice
  | SponsorsSlice
  | DatesSliceSlice
  | VideoSliceSlice
  | HeroSliceSlice
  | KeyDatesSlice
  | HeroBgSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *Content → Default → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Content field in *Content → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write your content here...
   * - **API ID Path**: content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation = ContentSliceDefault;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Primary content in *DatesSlice → Default → Primary*
 */
export interface DatesSliceSliceDefaultPrimary {
  /**
   * Heading field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Process
   * - **API ID Path**: dates_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dates_slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Date 1 field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: June 15, 2025
   * - **API ID Path**: dates_slice.default.primary.date_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_1: prismic.KeyTextField;

  /**
   * Participant 1 field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Dr. John Smith - Opening Keynote
   * - **API ID Path**: dates_slice.default.primary.participant_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  participant_1: prismic.KeyTextField;

  /**
   * Date 2 field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: June 16, 2025
   * - **API ID Path**: dates_slice.default.primary.date_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_2: prismic.KeyTextField;

  /**
   * Participant 2 field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Prof. Jane Doe - Research Presentation
   * - **API ID Path**: dates_slice.default.primary.participant_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  participant_2: prismic.KeyTextField;

  /**
   * Date 3 field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: June 17, 2025
   * - **API ID Path**: dates_slice.default.primary.date_3
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_3: prismic.KeyTextField;

  /**
   * Participant 3 field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Dr. Michael Johnson - Panel Discussion
   * - **API ID Path**: dates_slice.default.primary.participant_3
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  participant_3: prismic.KeyTextField;

  /**
   * Date 4 field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: June 18, 2025
   * - **API ID Path**: dates_slice.default.primary.date_4
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_4: prismic.KeyTextField;

  /**
   * Participant 4 field in *DatesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Prof. Sarah Wilson - Closing Remarks
   * - **API ID Path**: dates_slice.default.primary.participant_4
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  participant_4: prismic.KeyTextField;
}

/**
 * Default variation for DatesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DatesSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DatesSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DatesSlice*
 */
type DatesSliceSliceVariation = DatesSliceSliceDefault;

/**
 * DatesSlice Shared Slice
 *
 * - **API ID**: `dates_slice`
 * - **Description**: DatesSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DatesSliceSlice = prismic.SharedSlice<
  "dates_slice",
  DatesSliceSliceVariation
>;

/**
 * Primary content in *FaqSlice → Default → Primary*
 */
export interface FaqSliceSliceDefaultPrimary {
  /**
   * Heading field in *FaqSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Frequently Asked Questions
   * - **API ID Path**: faq_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *FaqSlice → Items*
 */
export interface FaqSliceSliceDefaultItem {
  /**
   * Question field in *FaqSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the question
   * - **API ID Path**: faq_slice.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the answer
   * - **API ID Path**: faq_slice.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FaqSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceSliceDefaultPrimary>,
  Simplify<FaqSliceSliceDefaultItem>
>;

/**
 * Slice variation for *FaqSlice*
 */
type FaqSliceSliceVariation = FaqSliceSliceDefault;

/**
 * FaqSlice Shared Slice
 *
 * - **API ID**: `faq_slice`
 * - **Description**: FaqSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceSlice = prismic.SharedSlice<
  "faq_slice",
  FaqSliceSliceVariation
>;

/**
 * Item in *HeroBgSlice → Default → Primary → Logos*
 */
export interface HeroBgSliceDefaultPrimaryLogosItem {
  /**
   * Logo field in *HeroBgSlice → Default → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_bg.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link field in *HeroBgSlice → Default → Primary → Logos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://
   * - **API ID Path**: hero_bg.default.primary.logos[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *HeroBgSlice → Default → Primary*
 */
export interface HeroBgSliceDefaultPrimary {
  /**
   * Background Image field in *HeroBgSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_bg.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Large Decorative Text field in *HeroBgSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: AGA26
   * - **API ID Path**: hero_bg.default.primary.large_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  large_text: prismic.KeyTextField;

  /**
   * Title field in *HeroBgSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: The 26th Annual General Assembly
   * - **API ID Path**: hero_bg.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroBgSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Human-centred digital oceans...
   * - **API ID Path**: hero_bg.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Date (short) field in *HeroBgSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: October 5 - 10 2026
   * - **API ID Path**: hero_bg.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Location (short) field in *HeroBgSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Split, CROATIA
   * - **API ID Path**: hero_bg.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Overlay style field in *HeroBgSlice → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_bg.default.primary.overlay
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  overlay: prismic.SelectField<"dark-blue" | "soft-blue" | "none">;

  /**
   * Logos field in *HeroBgSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_bg.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logos: prismic.GroupField<Simplify<HeroBgSliceDefaultPrimaryLogosItem>>;
}

/**
 * Default variation for HeroBgSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBgSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBgSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBgSlice*
 */
type HeroBgSliceVariation = HeroBgSliceDefault;

/**
 * HeroBgSlice Shared Slice
 *
 * - **API ID**: `hero_bg`
 * - **Description**: Large hero with background image, oversized decorative text and event meta.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBgSlice = prismic.SharedSlice<"hero_bg", HeroBgSliceVariation>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Heading field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your heading
   * - **API ID Path**: hero_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your subheading
   * - **API ID Path**: hero_slice.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Background Image field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Primary Button Text field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get Started
   * - **API ID Path**: hero_slice.default.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * Primary Button Link field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Text field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn More
   * - **API ID Path**: hero_slice.default.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Logo field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *KeyDates → Default → Primary*
 */
export interface KeyDatesSliceDefaultPrimary {
  /**
   * Heading field in *KeyDates → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter heading...
   * - **API ID Path**: key_dates.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *KeyDates → Items*
 */
export interface KeyDatesSliceDefaultItem {
  /**
   * Date field in *KeyDates → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 1 December
   * - **API ID Path**: key_dates.items[].date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Content field in *KeyDates → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter content for this date
   * - **API ID Path**: key_dates.items[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for KeyDates Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type KeyDatesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<KeyDatesSliceDefaultPrimary>,
  Simplify<KeyDatesSliceDefaultItem>
>;

/**
 * Slice variation for *KeyDates*
 */
type KeyDatesSliceVariation = KeyDatesSliceDefault;

/**
 * KeyDates Shared Slice
 *
 * - **API ID**: `key_dates`
 * - **Description**: Key dates timeline / grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type KeyDatesSlice = prismic.SharedSlice<
  "key_dates",
  KeyDatesSliceVariation
>;

/**
 * Primary content in *SmallHero → Default → Primary*
 */
export interface SmallHeroSliceDefaultPrimary {
  /**
   * Heading field in *SmallHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the heading...
   * - **API ID Path**: small_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *SmallHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the description...
   * - **API ID Path**: small_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Color field in *SmallHero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose background color
   * - **API ID Path**: small_hero.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<
    "Default" | "Gray" | "Brand" | "Dark" | "Navy"
  >;
}

/**
 * Default variation for SmallHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SmallHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmallHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SmallHero*
 */
type SmallHeroSliceVariation = SmallHeroSliceDefault;

/**
 * SmallHero Shared Slice
 *
 * - **API ID**: `small_hero`
 * - **Description**: SmallHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SmallHeroSlice = prismic.SharedSlice<
  "small_hero",
  SmallHeroSliceVariation
>;

/**
 * Primary content in *Sponsors → Default → Primary*
 */
export interface SponsorsSliceDefaultPrimary {
  /**
   * Heading field in *Sponsors → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Trusted by the world's leading companies
   * - **API ID Path**: sponsors.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *Sponsors → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Join the companies that trust us
   * - **API ID Path**: sponsors.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;
}

/**
 * Primary content in *Sponsors → Items*
 */
export interface SponsorsSliceDefaultItem {
  /**
   * Logo field in *Sponsors → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.items[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Company Name field in *Sponsors → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Company name for alt text
   * - **API ID Path**: sponsors.items[].company_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;
}

/**
 * Default variation for Sponsors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SponsorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SponsorsSliceDefaultPrimary>,
  Simplify<SponsorsSliceDefaultItem>
>;

/**
 * Slice variation for *Sponsors*
 */
type SponsorsSliceVariation = SponsorsSliceDefault;

/**
 * Sponsors Shared Slice
 *
 * - **API ID**: `sponsors`
 * - **Description**: Sponsors
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SponsorsSlice = prismic.SharedSlice<
  "sponsors",
  SponsorsSliceVariation
>;

/**
 * Primary content in *VideoSlice → Default → Primary*
 */
export interface VideoSliceSliceDefaultPrimary {
  /**
   * Heading field in *VideoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your heading
   * - **API ID Path**: video_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *VideoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your content
   * - **API ID Path**: video_slice.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  content: prismic.KeyTextField;

  /**
   * YouTube Video ID field in *VideoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., oRI37cOPBQQ
   * - **API ID Path**: video_slice.default.primary.youtube_video_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  youtube_video_id: prismic.KeyTextField;

  /**
   * Custom Thumbnail Image (Optional) field in *VideoSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_slice.default.primary.thumbnail_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail_image: prismic.ImageField<never>;
}

/**
 * Default variation for VideoSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoSlice*
 */
type VideoSliceSliceVariation = VideoSliceSliceDefault;

/**
 * VideoSlice Shared Slice
 *
 * - **API ID**: `video_slice`
 * - **Description**: VideoSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceSlice = prismic.SharedSlice<
  "video_slice",
  VideoSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      DatesSliceSlice,
      DatesSliceSliceDefaultPrimary,
      DatesSliceSliceVariation,
      DatesSliceSliceDefault,
      FaqSliceSlice,
      FaqSliceSliceDefaultPrimary,
      FaqSliceSliceDefaultItem,
      FaqSliceSliceVariation,
      FaqSliceSliceDefault,
      HeroBgSlice,
      HeroBgSliceDefaultPrimaryLogosItem,
      HeroBgSliceDefaultPrimary,
      HeroBgSliceVariation,
      HeroBgSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      KeyDatesSlice,
      KeyDatesSliceDefaultPrimary,
      KeyDatesSliceDefaultItem,
      KeyDatesSliceVariation,
      KeyDatesSliceDefault,
      SmallHeroSlice,
      SmallHeroSliceDefaultPrimary,
      SmallHeroSliceVariation,
      SmallHeroSliceDefault,
      SponsorsSlice,
      SponsorsSliceDefaultPrimary,
      SponsorsSliceDefaultItem,
      SponsorsSliceVariation,
      SponsorsSliceDefault,
      VideoSliceSlice,
      VideoSliceSliceDefaultPrimary,
      VideoSliceSliceVariation,
      VideoSliceSliceDefault,
    };
  }
}
