// Code generated by Prismic. DO NOT EDIT.

import Content from "./ContentSlice";
import Cta from "./Cta";
import DatesSlice from "./DatesSlice";
import FaqSlice from "./FaqSlice";
import HeroBgSlice from "./HeroBgSlice";
import HeroSlice from "./HeroSlice";
import KeyDates from "./KeyDatesSlice";
import Programme from "./Programme";
import RegistrationFees from "./RegistrationFeesSlice";
import SmallHero from "./SmallHeroSlice";
import Sponsors from "./SponsorsSlice";
import VideoSlice from "./VideoSlice";

export const components = {
	content: Content,
	cta: Cta,
	dates_slice: DatesSlice,
	faq_slice: FaqSlice,
	hero_bg: HeroBgSlice,
	hero_slice: HeroSlice,
	key_dates: KeyDates,
	programme: Programme,
	registration_fees: RegistrationFees,
	small_hero: SmallHero,
	sponsors: Sponsors,
	video_slice: VideoSlice
};