// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_slice: dynamic(() => import("./HeroSlice")),
  video_slice: dynamic(() => import("./VideoSlice")),
  dates_slice: dynamic(() => import("./DatesSlice")),
  sponsors: dynamic(() => import("./SponsorsSlice")),
  content: dynamic(() => import("./ContentSlice")),
  faq_slice: dynamic(() => import("./FaqSlice")),
  small_hero: dynamic(() => import("./SmallHeroSlice")),
  key_dates: dynamic(() => import("./KeyDatesSlice")),
};
